### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'keys'

### ISSUE THREAD

**Issue by xingjianfeng100** [phasebook/phasebook#16]
Hello,
I have successfully run the example datas, but suffered failure when using my own data with the same parameters. Could you help me to fix it?
 Here is my commend line: 
```
python /work/biosoft/phasebook/scripts/phasebook.py -i nanopore.pass.fastq.gz --min_cov 10 --sp_min_ovlplen 5000 --level 2 -t 32 -p ont -g large --sp_min_identity 0.85 --max_ovlps 100000 --max_het_snps 1 --min_allele_cov 6 --n_correct 40 --n_polish 10 --trim_ends True --ctg_asm naive --correct_mode hybrid --n_final_polish 4 --correct_mode hybrid -o result
```
and the log is 
```
sh: line 1: 144089 Segmentation fault      (core dumped) whatshap phase -o ....../result/3.cluster/c32/32.phased.vcf --reference ....../result/3.cluster/c32/32.ref.polished.fa --ignore-read-groups ....../result/3.cluster/c32/32.nophase.vcf ....../result/3.cluster/c32/32.bam > /dev/null 2>&1
sh: line 1: 144093 Segmentation fault      (core dumped) whatshap phase -o ....../result/3.cluster/c25/25.phased.vcf --reference ....../result/3.cluster/c25/25.ref.polished.fa --ignore-read-groups ....../result/3.cluster/c25/25.nophase.vcf ....../result/3.cluster/c25/25.bam > /dev/null 2>&1

......
......

ls: cannot access ....../result/3.cluster/c30/hap*/*: No such file or directory
ls: cannot access ....../result/3.cluster/c31/hap*/*: No such file or directory

......
......


Run CONSENT correction module command:
....../phasebook/scripts/../tools/CONSENT/CONSENT-correct -j 1 --in ....../result/3.cluster/c2/hap1/2.correct_39.fa --out ....../result/3.cluster/c2/hap1/2.correct_40.fa --type ONT --tmpdir ....../result/3.cluster/c2/hap1 >....../result/3.cluster/c2/hap1/2.log 2>&1
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "....../.conda/envs/phasebook/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "....../.conda/envs/phasebook/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "....../phasebook/scripts/assembly.py", line 161, in get_superead
    for hap in hap2reads.keys():
AttributeError: 'NoneType' object has no attribute 'keys'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "....../phasebook/scripts/phasebook.py", line 379, in <module>
    sys.exit(main())
  File "....../phasebook/scripts/phasebook.py", line 312, in main
    args.correct_mode)
  File "....../phasebook/scripts/parallel.py", line 17, in run_on_local
    pool.map(get_superead, params, chunksize=1)  # ordered
  File "....../.conda/envs/xjf_phasebook/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "....../.conda/envs/xjf_phasebook/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
AttributeError: 'NoneType' object has no attribute 'keys'
```
I look forward to your reply. Thank you!

**Comment by DengHAU** [comment]
Have you solved the problem?

**Comment by xingjianfeng100** [comment]
sorry, I have forgotten the solution that has been adopted, for it was so long ago; I have the impression, I change the  environment variable for python maybe.

**Comment by dasn588** [comment]
Hi,
I tried to run the program using 11K fasta read sequences from nanopore sequencing data but encountered following error. Please help me in resolving the issue.

##Command used:
python3 phasebook.py -i reads.fasta -t 40 -p ont -g small -x -o phasebook_consensus_phasing

##Error 
assembly.py[line:153] - INFO: cluster:1 reads phasing started...
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/miniconda3/envs/phasebook/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/miniconda3/envs/phasebook/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/phasebook/scripts/assembly.py", line 161, in get_superead
    for hap in hap2reads.keys():
AttributeError: 'NoneType' object has no attribute 'keys'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "phasebook.py", line 379, in <module>
    sys.exit(main())
  File "phasebook.py", line 312, in main
    args.correct_mode)
  File "/phasebook/scripts/parallel.py", line 17, in run_on_local
    pool.map(get_superead, params, chunksize=1)  # ordered
  File "/miniconda3/envs/phasebook/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/miniconda3/envs/phasebook/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
AttributeError: 'NoneType' object has no attribute 'keys'
