### ISSUE TITLE
Problems when running phasebook

### ISSUE THREAD

**Issue by DaiWeiKIB** [phasebook/phasebook#18]
Dear author

Thank you for your outstanding contribution for this program . I have some questions I'd like to ask you, if it's convenient for you.

When I run the sample data with 
` python /home/daiwei/phasebook/scripts/phasebook.py -i reads.fa -t 20 -p hifi -g small -x `
![image](https://user-images.githubusercontent.com/97493123/148877159-1cc7b0c3-7067-428b-b1e6-627d2fddefa3.png)
The program shows no errors and runs successfully. But the output contigs.fa(1.1M) shows a big difference from reference.fa(833K) mainly in size.

And when I run my own data, which can be assembled into decent contig by using the minimap2 default parameters, I got following problem.
![image](https://user-images.githubusercontent.com/97493123/148877572-7a3b1cee-f05a-461b-8dc0-bc699f6c0d6c.png)

(pb) [daiwei@localhost hy]$ python /home/daiwei/phasebook/scripts/phasebook.py -i "/home/daiwei/mitgenome/02/hy/02Tassmble.fasta" -t 20 -p ont -g small -x -o "/home/daiwei/mitgenome/01/hy/pb1/"
use preset parameters...
2022-01-11 11:16:50,612 - /home/daiwei/phasebook/scripts/phasebook.py[line:261] - INFO: splitting input fastx file into 1 subfiles...
2022-01-11 11:17:03,690 - /home/daiwei/phasebook/scripts/phasebook.py[line:269] - INFO: splitting finished.

2022-01-11 11:17:03,691 - /home/daiwei/phasebook/scripts/phasebook.py[line:277] - INFO: computing all-vs-all read overlaps...
ONT platform
thread 'main' panicked at 'File is probably empty: FileTooShort', src/file.rs:30:14
**note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace**
2022-01-11 11:17:13,586 - /home/daiwei/phasebook/scripts/phasebook.py[line:284] - INFO: computing overlaps finished.

2022-01-11 11:17:13,586 - /home/daiwei/phasebook/scripts/phasebook.py[line:289] - INFO: clustering reads...
/home/daiwei/mitgenome/01/hy/pb1//2.overlap/s1_s1.paf
reading overlap done...
2022-01-11 11:17:13,587 - /home/daiwei/phasebook/scripts/phasebook.py[line:298] - INFO: generating read and overlap files for each cluster...
2022-01-11 11:17:15,725 - /home/daiwei/phasebook/scripts/phasebook.py[line:308] - INFO: stage1 assembly: assemble raw reads for each cluster...
2022-01-11 11:17:15,876 - /home/daiwei/phasebook/scripts/phasebook.py[line:318] - INFO: concatenate super reads sequences for all clusters...
cat: '/home/daiwei/mitgenome/01/hy/pb1//3.cluster/c*/*.supereads.fa': No such file or directory
2022-01-11 11:17:15,885 - /home/daiwei/phasebook/scripts/phasebook.py[line:323] - INFO: stage1 assembly has been finished.
2022-01-11 11:17:15,885 - /home/daiwei/phasebook/scripts/phasebook.py[line:331] - INFO: Using rb method for super reads assembly...
[M::mm_idx_gen::0.001*3.50] collected minimizers
[M::mm_idx_gen::0.004*8.89] sorted minimizers
[M::main::0.004*8.86] loaded/built the index for 0 target sequence(s)
[M::mm_mapopt_update::0.004*8.76] mid_occ = 1
[M::mm_idx_stat] kmer size: 19; skip: 5; is_hpc: 1; #seq: 0
[M::mm_idx_stat::0.004*8.69] distinct minimizers: 0 (-nan% are singletons); average occurrences: -nan; average spacing: -nan; total length: 0
[M::main] Version: 2.18-r1015
[M::main] CMD: minimap2 -cx ava-pb -Hk19 -Xw5 -m100 -g10000 --max-chain-skip 25 --end-bonus 100 -t 20 /home/daiwei/mitgenome/01/hy/pb1//all.supereads.fa /home/daiwei/mitgenome/01/hy/pb1//all.supereads.fa
[M::main] Real time: 0.005 sec; CPU: 0.039 sec; Peak RSS: 0.005 GB
**No satisfied overlap found between super reads, program finished.**
The final output haplotype aware contigs are here :
/home/daiwei/mitgenome/01/hy/pb1//4.asm_supereads/../contigs.fa

I would like to ask how to deal with such a situation. Thank you sincerely
@HaploKit
[phasebook.log](https://github.com/phasebook/phasebook/files/7843989/phasebook.log)

**Comment by phasebook** [comment]
Hi, thanks. I just updated some code in `scripts/`, could you please replace your old `scripts/` (no need to reinstall), then run again ? I guess this error occurs probably because of the failure of read overlap computation. If the sequencing coverage of your data is very high or your data size is large, you could try to run by splitting data first, say adding parameter `--nsplit 10`.

**Comment by DaiWeiKIB** [comment]
Thanks for your promptly reply and update

I replace my `scripts/` ,then run example data, it runs successfully. And rerun my data as follows

(pb) [daiwei@localhost ~]$ python "/home/daiwei/phasebook/scripts/phasebook.py" -i "/home/daiwei/mitgenome/01/hy/01mitassmble.fasta" -t 30 -p ont -g small -x -o "/home/daiwei/mitgenome/01/hy/pb/" --rm_tmp False
use preset parameters...
2022-01-11 15:28:12,606 - /home/daiwei/phasebook/scripts/phasebook.py[line:261] - INFO: splitting input fastx file into 1 subfiles...
2022-01-11 15:28:20,658 - /home/daiwei/phasebook/scripts/phasebook.py[line:269] - INFO: splitting finished.

2022-01-11 15:28:20,659 - /home/daiwei/phasebook/scripts/phasebook.py[line:277] - INFO: computing all-vs-all read overlaps...
ONT platform
[WARNING] the length database sequence '1_319' is 0
[WARNING] the length database sequence '501c19af-a8f2-4d0e-84a7-8d265e24112f' is 0
[WARNING] the length database sequence '1_412' is 0
[WARNING] the length database sequence 'cb8ccbe2-9769-41c1-a738-841276535c23' is 0
[WARNING] the length database sequence '1_584' is 0
[WARNING] the length database sequence '429151b3-09d1-4a1f-8cbd-d7975616f13e' is 0
[WARNING] the length database sequence '1_673' is 0
[WARNING] the length database sequence '9e3a1875-e764-4161-91eb-12f1fc21da42' is 0
[WARNING] the length database sequence '1_792' is 0
[WARNING] the length database sequence 'bbb977e4-1b69-426a-9645-878f418721f0' is 0
[WARNING] the length database sequence '1_1016' is 0
[WARNING] the length database sequence 'b3edfd8c-3ae8-471c-a2be-75d6374c7671' is 0
[WARNING] the length database sequence '1_1412' is 0
[WARNING] the length database sequence 'dd0fbbc4-13da-4fe8-b72c-1854d8f4dc72' is 0
[WARNING] the length database sequence '1_1521' is 0
[WARNING] the length database sequence 'ea5a4459-5f86-412b-b50f-7be4e22606f1' is 0
[WARNING] the length database sequence '1_1709' is 0
[WARNING] the length database sequence '647226dc-1138-4040-ae5e-007feb7866a8' is 0
[WARNING] the length database sequence '1_1933' is 0
[WARNING] the length database sequence '75c1358d-d9ee-403c-93a6-493b8a2ceb43' is 0
[WARNING] the length database sequence '1_2055' is 0
[WARNING] the length database sequence 'acef6f90-c41b-4391-a180-f625dc7d17be' is 0
[WARNING] the length database sequence '1_2186' is 0
[WARNING] the length database sequence 'c4767b21-fead-4087-ab41-fe029594db1e' is 0
[WARNING] the length database sequence '1_2307' is 0
[WARNING] the length database sequence 'abfbd30a-df00-4ebd-9508-2093b0971163' is 0
[WARNING] the length database sequence '1_2625' is 0
[WARNING] the length database sequence 'bbb25c7e-d706-4fd0-9542-942b1c96bc3c' is 0
[WARNING] the length database sequence '1_3265' is 0
[WARNING] the length database sequence '82b20faf-1497-414e-a0e1-12cb45ea7130' is 0
[WARNING] the length database sequence '1_3536' is 0
[WARNING] the length database sequence 'e11984cd-cf6b-4335-b515-4665cbe82f65' is 0
[WARNING] the length database sequence '1_3758' is 0
[WARNING] the length database sequence 'e9caad88-c25e-4199-b528-3988483e2e92' is 0
[WARNING] the length database sequence '1_3909' is 0
[WARNING] the length database sequence 'c105d092-2a2b-4f31-a901-419c7fa7ab52' is 0
[WARNING] the length database sequence '1_4451' is 0
[WARNING] the length database sequence '7fba2834-8b6f-4023-83e4-19006e2042d1' is 0
[WARNING] the length database sequence '1_4884' is 0
[WARNING] the length database sequence '6ef7587c-db2a-47eb-a7cc-a532b90ba3f7' is 0
[WARNING] the length database sequence '1_5126' is 0
[WARNING] the length database sequence '6761c7b4-572a-47de-886a-e3ad24e340e1' is 0
[WARNING] the length database sequence '1_5369' is 0
[WARNING] the length database sequence '6c7976f7-3816-49ea-a6c6-666b25286c52' is 0
[WARNING] the length database sequence '1_5615' is 0
[WARNING] the length database sequence '72ec498d-ba18-4f10-ab33-56460abf16c5' is 0
[WARNING] the length database sequence '1_5815' is 0
[WARNING] the length database sequence 'b039bded-b7a9-47ba-85a7-8763c0f69a53' is 0
[WARNING] the length database sequence '1_5922' is 0
[WARNING] the length database sequence 'bc34134f-baa8-4a2c-8d40-308acaa49d31' is 0
[WARNING] the length database sequence '1_6518' is 0
[WARNING] the length database sequence '2104fdc3-5b3e-4e53-9234-60ef741b9f6e' is 0
[WARNING] the length database sequence '1_6768' is 0
[WARNING] the length database sequence '10e397d1-b72f-4a55-b5d3-eea7b2602763' is 0
[WARNING] the length database sequence '1_7107' is 0
[WARNING] the length database sequence '2dff78f8-7587-46a9-87d9-01701708cce0' is 0
[WARNING] the length database sequence '1_7515' is 0
[WARNING] the length database sequence '06c8f46d-45dd-4c75-9a1b-ae6d3d9ce045' is 0
[WARNING] the length database sequence '1_7637' is 0
[WARNING] the length database sequence 'c26b5309-68a0-4d04-8698-7b1457a15a6a' is 0
[WARNING] the length database sequence '1_7932' is 0
[WARNING] the length database sequence 'fdb44e08-4bb6-421a-b0e7-5308d52f6991' is 0
[WARNING] the length database sequence '1_8411' is 0
[WARNING] the length database sequence '1f0f69ea-f677-43dd-b667-54dc104d4d9b' is 0
[WARNING] the length database sequence '1_9087' is 0
[WARNING] the length database sequence '5d3af24b-7994-4c8c-971e-d79e42930f81' is 0
[WARNING] the length database sequence '1_9302' is 0
[WARNING] the length database sequence '8f671351-a772-4845-9ebc-b64330e91065' is 0
[WARNING] the length database sequence '1_10366' is 0
[WARNING] the length database sequence '3d739f67-f802-4db2-a69c-e9d0727183cb' is 0
[WARNING] the length database sequence '1_10515' is 0
[WARNING] the length database sequence 'd7d8b16f-3240-4224-8c09-e983f63abc11' is 0
[WARNING] the length database sequence '1_10771' is 0
[WARNING] the length database sequence '8cbe550b-84fb-4ef1-8ae6-51d8f9f123e6' is 0
[WARNING] the length database sequence '1_11085' is 0
[WARNING] the length database sequence '739d8060-b9c7-4b23-aa66-2eb77a148c9a' is 0
[WARNING] the length database sequence '1_11410' is 0
[WARNING] the length database sequence 'a428f36b-b3eb-466c-8af4-acab8338083e' is 0
[WARNING] the length database sequence '1_11530' is 0
[WARNING] the length database sequence 'abf14163-a19b-4d46-bf96-525b3cb7b23b' is 0
[WARNING] the length database sequence '1_11627' is 0
[WARNING] the length database sequence 'c8645669-f095-46ed-846e-6ea643e18d8b' is 0
[WARNING] the length database sequence '1_12028' is 0
[WARNING] the length database sequence 'd6939dca-5e20-4138-b51f-35f754a216ff' is 0
[WARNING] the length database sequence '1_12115' is 0
[WARNING] the length database sequence 'cd24a150-2720-4d52-8cac-c1f46f864c75' is 0
[WARNING] the length database sequence '1_12286' is 0
[WARNING] the length database sequence 'd331c85e-839f-47ec-a6ae-0120e2b87987' is 0
[WARNING] the length database sequence '1_12420' is 0
[WARNING] the length database sequence '0d508d23-af8f-4bae-b436-81821cda726a' is 0
[WARNING] the length database sequence '1_12558' is 0
[WARNING] the length database sequence '26754b05-ac6e-485d-8382-344dc3939f9a' is 0
[WARNING] the length database sequence '1_13413' is 0
[WARNING] the length database sequence 'a3f394eb-e2aa-4511-8a6b-deba775b2cc4' is 0
[WARNING] the length database sequence '1_13738' is 0
[WARNING] the length database sequence 'e8f85cd4-7a21-46eb-92b0-fe887fe64952' is 0
[WARNING] the length database sequence '1_14295' is 0
[WARNING] the length database sequence '5c1ad5dc-7b98-4d06-b2bd-b87d021b12e3' is 0
[WARNING] the length database sequence '1_14409' is 0
[WARNING] the length database sequence '77dff876-b96f-4f41-8117-af8f359273f1' is 0
[WARNING] the length database sequence '1_14681' is 0
[WARNING] the length database sequence '8d9de89d-a98f-4942-93f8-d9def3f41527' is 0
[WARNING] the length database sequence '1_14923' is 0
[WARNING] the length database sequence 'b1a4c6e6-e9da-411a-8b1c-aa408c125336' is 0
[WARNING] the length database sequence '1_23983' is 0
[WARNING] the length database sequence 'bfd0af50-831f-4e5b-9865-14475289f4eb' is 0
[WARNING] the length database sequence '1_24092' is 0
[WARNING] the length database sequence '59a8032f-070a-49dc-a891-0cb167056277' is 0
[WARNING] the length database sequence '1_24200' is 0
[WARNING] the length database sequence '2b71ccc8-17c0-439a-a0e7-c92afed41468' is 0
[WARNING] the length database sequence '1_24514' is 0
[WARNING] the length database sequence 'b7db8bd8-35a7-49cf-91be-6cec920d312f' is 0
[WARNING] the length database sequence '1_24782' is 0
[WARNING] the length database sequence '8adb744a-3aa0-437d-9c07-8553afbc3124' is 0
[WARNING] the length database sequence '1_25133' is 0
[WARNING] the length database sequence 'a7e2a253-c34e-4a8e-ba0c-fd0c666fd6b6' is 0
[WARNING] the length database sequence '1_25225' is 0
[WARNING] the length database sequence 'f695adf8-8fb8-4520-bc2b-53d18d4b0942' is 0
[WARNING] the length database sequence '1_26207' is 0
[WARNING] the length database sequence 'ecd55f4e-3acd-440b-a445-e6e69fb10b7a' is 0
[WARNING] the length database sequence '1_26340' is 0
[WARNING] the length database sequence '66ed3ce2-5bc9-44e1-bcdb-560a9e699900' is 0
[WARNING] the length database sequence '1_26528' is 0
[WARNING] the length database sequence 'a04bdf72-d54b-452f-8ae0-636cc5942927' is 0
[WARNING] the length database sequence '1_26681' is 0
[WARNING] the length database sequence '3af37462-63d2-4f98-a90b-11aa0345b074' is 0
[WARNING] the length database sequence '1_27285' is 0
[WARNING] the length database sequence 'b7361e86-9b46-40f8-9531-0bf36d9042a8' is 0
[WARNING] the length database sequence '1_27691' is 0
[WARNING] the length database sequence '2819cbbe-3eb0-40d5-976c-b0d7de026c74' is 0
[WARNING] the length database sequence '1_28110' is 0
[WARNING] the length database sequence '796b57c1-83c4-4a4d-ba08-195988e57c82' is 0
[WARNING] the length database sequence '1_28607' is 0
[WARNING] the length database sequence '14bda604-3f93-4dc8-be12-b3c9146c9f6e' is 0
[WARNING] the length database sequence '1_28842' is 0
[WARNING] the length database sequence '5e2ff77b-a05e-4e84-af60-ec04bccae3fc' is 0
[WARNING] the length database sequence '1_29294' is 0
[WARNING] the length database sequence '01168ddb-7d3e-40a6-8d4e-2cf9392d2d65' is 0
[WARNING] the length database sequence '1_29758' is 0
[WARNING] the length database sequence '6b2704c8-9124-44fd-ad32-1e348bda20e8' is 0
[WARNING] the length database sequence '1_29925' is 0
[WARNING] the length database sequence '8703aadf-6f85-4dfb-aa8c-168adbcc6214' is 0
[WARNING] the length database sequence '1_30221' is 0
[WARNING] the length database sequence 'bd8e639e-ad93-4d37-9c5b-5c1c536261c8' is 0
[WARNING] the length database sequence '1_30984' is 0
[WARNING] the length database sequence 'cc8f0448-f921-4dbc-b22c-22bbc1c51ba6' is 0
[WARNING] the length database sequence '1_31543' is 0
[WARNING] the length database sequence 'c28257c1-0c24-4d2b-b651-0f9dd60b2472' is 0
[WARNING] the length database sequence '1_1290785' is 0
[WARNING] the length database sequence 'd0e61b32-daa7-4cc9-bbdb-756658454049' is 0
[WARNING] the length database sequence '1_1291262' is 0
[WARNING] the length database sequence '187609e3-3c0d-4377-9448-087a69b7610f' is 0
[WARNING] the length database sequence '1_1291436' is 0
[WARNING] the length database sequence '500ed5d8-47e8-4b11-be3d-a12de721a8a4' is 0
[WARNING] the length database sequence '1_1292260' is 0
[WARNING] the length database sequence '1ae794c5-dfe1-4fef-b011-f035a50e57bf' is 0
[WARNING] the length database sequence '1_1292478' is 0
[WARNING] the length database sequence 'de034776-6c9e-4eea-94fd-bab88c7def76' is 0
[M::mm_idx_gen::4.185*1.24] collected minimizers
[M::mm_idx_gen::4.496*2.00] sorted minimizers
[M::main::4.496*2.00] loaded/built the index for 1296347 target sequence(s)
[M::mm_mapopt_update::4.693*1.96] mid_occ = 151
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 1296347
[M::mm_idx_stat::4.854*1.93] distinct minimizers: 8139291 (78.61% are singletons); average occurrences: 2.367; average spacing: 4.009; total length: 77221156
[M::worker_pipeline::8.199*10.37] mapped 1296347 sequences
[M::main] Version: 2.18-r1015
[M::main] CMD: minimap2 -cx ava-ont -t 30 /home/daiwei/mitgenome/01/hy/pb//1.split_fastx/s1.fa /home/daiwei/mitgenome/01/hy/pb//1.split_fastx/s1.fa
[M::main] Real time: 8.298 sec; CPU: 85.115 sec; Peak RSS: 1.167 GB
thread 'main' panicked at 'File is probably empty: FileTooShort', src/file.rs:30:14
**note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace**
Traceback (most recent call last):
  File "/home/daiwei/phasebook/scripts/phasebook.py", line 379, in <module>
    sys.exit(main())
  File "/home/daiwei/phasebook/scripts/phasebook.py", line 282, in main
    args.min_identity, args.max_oh, args.oh_ratio)
  File "/home/daiwei/phasebook/scripts/utils.py", line 156, in compute_ovlps
    max_oh, oh_ratio)
  File "/home/daiwei/phasebook/scripts/utils.py", line 116, in compute_ovlp
    raise RuntimeError("failed to compute the read overlaps")
**RuntimeError: failed to compute the read overlaps**

Even adding parameter --nsplit 10 this error report shows the same.

**Comment by phasebook** [comment]
Sorry, please try to use non-wrapped FASTA (one read per line) and run again, like this:

'''
\>read1
AACGGTACG
\>read2
TATTAAGGC
\>read3
AGGGCCGAATT
'''

**Comment by DaiWeiKIB** [comment]
Thanks for your kindly note. 

I run `awk '!/^>/ { printf "%s", $0; n = "\n" } /^>/ { print n $0; n = "" } END { printf "%s", n }' test.fa` to change the format about my data. And when I adding parameter `--nsplit 10` to rerun . The result shows like 

(pb) [daiwei@localhost test]$ python "/home/daiwei/phasebook/scripts/phasebook.py" -i "/home/daiwei/mitgenome/09/hy/09assmble.fa" -t 20 -p ont -g small -x -o "/home/daiwei/mitgenome/09/test/" --nsplit 10
use preset parameters...
2022-01-12 20:51:09,935 - /home/daiwei/phasebook/scripts/phasebook.py[line:261] - INFO: splitting input fastx file into 10 subfiles...
2022-01-12 20:51:11,588 - /home/daiwei/phasebook/scripts/phasebook.py[line:269] - INFO: splitting finished.

2022-01-12 20:51:11,588 - /home/daiwei/phasebook/scripts/phasebook.py[line:277] - INFO: computing all-vs-all read overlaps...
ONT platform
[M::mm_idx_gen::2.110*1.00] collected minimizers
[M::mm_idx_gen::2.460*1.59] sorted minimizers
[M::main::2.460*1.59] loaded/built the index for 1000 target sequence(s)
[M::mm_mapopt_update::2.582*1.56] mid_occ = 46
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 1000
[M::mm_idx_stat::2.673*1.54] distinct minimizers: 5044650 (84.18% are singletons); average occurrences: 1.744; average spacing: 2.938; total length: 25840183
[M::worker_pipeline::3.183*3.84] mapped 1000 sequences
[M::main] Version: 2.18-r1015
[M::main] CMD: minimap2 -cx ava-ont -t 20 /home/daiwei/mitgenome/09/test//1.split_fastx/s1.fa /home/daiwei/mitgenome/09/test//1.split_fastx/s2.fa
[M::main] Real time: 3.232 sec; CPU: 12.270 sec; Peak RSS: 0.473 GB
thread 'main' panicked at 'File is probably empty: FileTooShort', src/file.rs:30:14
**note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace**
Traceback (most recent call last):
  File "/home/daiwei/phasebook/scripts/phasebook.py", line 379, in <module>
    sys.exit(main())
  File "/home/daiwei/phasebook/scripts/phasebook.py", line 282, in main
    args.min_identity, args.max_oh, args.oh_ratio)
  File "/home/daiwei/phasebook/scripts/utils.py", line 156, in compute_ovlps
    max_oh, oh_ratio)
  File "/home/daiwei/phasebook/scripts/utils.py", line 116, in compute_ovlp
    raise RuntimeError("failed to compute the read overlaps")
**RuntimeError: failed to compute the read overlaps**

The same problem seems still remain. I assume it's probably because the parameter `--nsplit 10` . With I delete it and rerun, it takes quite a few time which cause me reply so late, to generate some fine contigs larger about 10 times than flye generated.

**Comment by HaploKit** [comment]
Thanks, I also tested with default parameters, it generated >5Mb phased contigs. You said the truth diploid genome size should be: 2Mb x 2 =4Mb ?  It is prone to yield duplicated sequences because of ploidy-aware setting. To reduce the final contig size, You could try to relax related thresholds in the super read overlap graph based assembly step.

**Comment by DaiWeiKIB** [comment]
Thanks for your guiding.
