### ISSUE TITLE
something error when run phasebook on hpc

### ISSUE THREAD

**Issue by Xiaoguang-Shi** [phasebook/phasebook#19]
hello,
I get an error when I run the step`generate scripts used to get super reads for each clusters`. The previous run generated $i.fa and $ipaf files in each C$i folder.
The code is
```
python ~/phasebook-master/scripts/generate_super_reads_on_hpc.py 1 phasebook/out/3.cluster ont 10.0 1000 1 2 1 True racon True msa ~/miniconda3/envs/phasebook/bin/
```
error massage
```
Traceback (most recent call last):
  File "~/phasebook-master/scripts/generate_super_reads_on_hpc.py", line 35, in <module>
    get_superead([i, outdir, type, min_cov, max_tip_len, n_correct, n_polish, rm_trans, trim_ends,polish_tool,rm_tmp,correct_mode,binpath])
  File "~/phasebook-master/scripts/assembly.py", line 143, in get_superead
    ref = assemble_raw_reads(i, fasta, paf, outdir, max_tip_len, rm_trans,binpath)
  File "~phasebook-master/scripts/assembly.py", line 117, in assemble_raw_reads
    G = construct_digraph(digraph_file)
  File "~/phasebook-master/scripts/assembly.py", line 89, in construct_digraph
    with open(digraph_file) as fr:
FileNotFoundError: [Errno 2] No such file or directory: '/phasebook/out/3.cluster/c1/digraph.txt'
```
It seems that some files are not generated properly.
This is the content under `3.cluster/c1/`
```
0       1.corrected.fa
9.7M    1.fa
0       1.log
2.6M    1.paf
9.7M    1.renamed.fa
0       1.renamed.paf
0       nonedge_overlaps.txt
0       overlaps.savage
0       overlaps.sfo
9.0K    reads.id_map
9.7M    reads.renamed.fa
0       reads.renamed.paf
20M     singles.fastq
1.5K    viralquasispecies.log
```

**Comment by HaploKit** [comment]
Hi, according to `FileNotFoundError: [Errno 2] No such file or directory: '/phasebook/out/3.cluster/c1/digraph.txt'
`, could you please try to use the absolute path of `phasebook/out/3.cluster` in the code ？

**Comment by Xiaoguang-Shi** [comment]
I use absolute path and the problem still exists. The file `1.renamed.paf` is empty, I don't know if it has anything to do with this.

**Comment by Xiaoguang-Shi** [comment]
When I am run `python assembly.py `,its shows that:

```
Traceback (most recent call last):
  File "assembly.py", line 10, in <module>
    from supereads import filter_ovlp_based_on_reads_parallel
  File "/public/home/xiaoguang/biosoft/nanopore/phasebook/scripts/supereads.py", line 6, in <module>
    import assembly
  File "/public/home/xiaoguang/biosoft/nanopore/phasebook/scripts/assembly.py", line 10, in <module>
    from supereads import filter_ovlp_based_on_reads_parallel
ImportError: cannot import name 'filter_ovlp_based_on_reads_parallel' from 'supereads' (/public/home/xiaoguang/biosoft/nanopore/phasebook/scripts/supereads.py)
```

**Comment by HaploKit** [comment]
Did you follow the script `run_phasebook_on_hpc.sh`  when running on HPC ?

**Comment by Xiaoguang-Shi** [comment]
I modified the code in the qsub section to fit slurm.The previous code is as follows:

```
python /public/home/xiaoguang/biosoft/phasebook-master/scripts/phasebook.py -i GS005.fa -t 40 -p ont -g large -x 
input=GS005.fa
srcpath=/public/home/xiaoguang/biosoft/phasebook-master/scripts
threads=40
outdir=`pwd`/out

python $srcpath/phasebook_hpc.py -i $input -o $outdir --nsplit 200 -t $threads -g large --min_cov 10 --min_identity 0.0 --min_read_len 1000 --min_sread_len 5000 --min_ovlp_len 1000 --n_correct 1 --n_polish 2 --platform ont --min_cluster_size 10 --level 2 --rm_trans 1 --sort_by_len True --trim_ends True --rename True --sp_min_ovlplen 5000 --sp_min_identity 0.95 --sp_oh 10 --ctg_asm naive --max_het_snps 0 --min_allele_cov 8 --n_final_polish 1 --polish_tool racon --rm_tmp True --limited_times 3 --max_ovlps 1000 --max_cluster_size 1000 --correct_mode msa --super_ovlp_fast True --stage 1

perl -e 'my@fas;for my$fa( `ls $ARGV[0]/1.split_fastx/`){chomp $fa;push @fas,$fa;} for my$i(0..$#fas){print "print "#!/bin/bash\n#SBATCH --exclusive\n#SBATCH --partition=SVC\nminimap2 -x ava-ont -t 40  $ARGV[0]/../reads.fa $ARGV[0]/1.split_fastx/$fas[$i] 2>/dev/null |cut -f 1-12 |awk '\''\$11>=1000 && \$10/\$11 >=0.0 '\'' |fpa drop -i -m   >$ARGV[0]/2.overlap/ovlp.$i.paf\n";  } '  $outdir $input  >compute_overlaps_hpc.sh

split -l 4 -a 3 compute_overlaps_hpc.sh  -d sub-ovlp

for i in sub-ovlp*;do sbatch  $i;done

python $srcpath/phasebook_hpc.py -i $input -o $outdir --nsplit 200 -t $threads -g large --min_cov 10 --min_identity 0.0 --min_read_len 1000 --min_sread_len 5000 --min_ovlp_len 1000 --n_correct 1 --n_polish 2 --platform ont --min_cluster_size 10 --level 2 --rm_trans 1 --sort_by_len True --trim_ends True --rename True --sp_min_ovlplen 5000 --sp_min_identity 0.95 --sp_oh 10 --ctg_asm naive --max_het_snps 0 --min_allele_cov 8 --n_final_polish 1 --polish_tool racon --rm_tmp True --limited_times 3 --max_ovlps 1000 --max_cluster_size 1000 --correct_mode msa --super_ovlp_fast True --stage 2

for i in {1..59340};do
echo -e '#!/bin/bash\n#SBATCH -N 1\n#SBATCH -n 6' >>  sub-generate${i}
cat generate_super_reads_hpc.sh |awk '{if($3==num) print $0}' num=$i |sed s/'/prj/whatshap-denovo/software/miniconda3/bin/python'/python/g  >> sub-generate${i}
done
```
