### ISSUE TITLE
crash during cluster processing

### ISSUE THREAD

**Issue by HMPNK** [phasebook/phasebook#27]
Hi I am trying to assemble a 1Gb genome. Phasebook stopped with:

.....
2022-05-19 01:01:12,129 - /home/kuhl/phasebook/scripts/assembly.py[line:150] - INFO: cluster:9593 variant calling started...
2022-05-19 01:01:12,617 - /home/kuhl/phasebook/scripts/assembly.py[line:150] - INFO: cluster:9595 variant calling started...
2022-05-19 01:01:12,617 - /home/kuhl/phasebook/scripts/assembly.py[line:150] - INFO: cluster:9596 variant calling started...
2022-05-19 01:01:12,680 - /home/kuhl/phasebook/scripts/assembly.py[line:153] - INFO: cluster:9593 reads phasing started...
2022-05-19 01:01:13,084 - /home/kuhl/phasebook/scripts/assembly.py[line:153] - INFO: cluster:9596 reads phasing started...
2022-05-19 01:01:13,198 - /home/kuhl/phasebook/scripts/assembly.py[line:153] - INFO: cluster:9595 reads phasing started...
2022-05-19 01:01:13,242 - /home/kuhl/phasebook/scripts/assembly.py[line:150] - INFO: cluster:9597 variant calling started...
2022-05-19 01:01:13,295 - /home/kuhl/phasebook/scripts/assembly.py[line:150] - INFO: cluster:9594 variant calling started...
2022-05-19 01:01:13,411 - /home/kuhl/phasebook/scripts/assembly.py[line:150] - INFO: cluster:9600 variant calling started...
2022-05-19 01:01:13,485 - /home/kuhl/phasebook/scripts/assembly.py[line:150] - INFO: cluster:9601 variant calling started...
2022-05-19 01:01:13,486 - /home/kuhl/phasebook/scripts/assembly.py[line:150] - INFO: cluster:9598 variant calling started...
2022-05-19 01:01:13,797 - /home/kuhl/phasebook/scripts/assembly.py[line:153] - INFO: cluster:9594 reads phasing started...
2022-05-19 01:01:13,868 - /home/kuhl/phasebook/scripts/assembly.py[line:153] - INFO: cluster:9597 reads phasing started...
2022-05-19 01:01:13,907 - /home/kuhl/phasebook/scripts/assembly.py[line:153] - INFO: cluster:9600 reads phasing started...
2022-05-19 01:01:13,991 - /home/kuhl/phasebook/scripts/assembly.py[line:153] - INFO: cluster:9601 reads phasing started...
2022-05-19 01:01:14,063 - /home/kuhl/phasebook/scripts/assembly.py[line:153] - INFO: cluster:9598 reads phasing started...
[main_samview] fail to read the header from "-".
[main_samview] fail to read the header from "-".
[main_samview] fail to read the header from "-".
[main_samview] fail to read the header from "-".
[main_samview] fail to read the header from "-".
[main_samview] fail to read the header from "-".
[main_samview] fail to read the header from "-".
2022-05-19 01:01:48,951 - /home/kuhl/phasebook/scripts/assembly.py[line:150] - INFO: cluster:9410 variant calling started...
2022-05-19 01:01:49,521 - /home/kuhl/phasebook/scripts/assembly.py[line:153] - INFO: cluster:9410 reads phasing started...
[main_samview] fail to read the header from "-".
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/kuhl/miniconda2/envs/phasebook/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/kuhl/miniconda2/envs/phasebook/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/kuhl/phasebook/scripts/assembly.py", line 154, in get_superead
    hap2reads = phase_reads(i, vcf, bam, ref, outdir, True,binpath)
  File "/home/kuhl/phasebook/scripts/phasing.py", line 74, in phase_reads
    read = line.strip().split()[0]
IndexError: list index out of range
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kuhl/phasebook/scripts/phasebook.py", line 379, in <module>
    sys.exit(main())
  File "/home/kuhl/phasebook/scripts/phasebook.py", line 312, in main
    args.correct_mode)
  File "/home/kuhl/phasebook/scripts/parallel.py", line 17, in run_on_local
    pool.map(get_superead, params, chunksize=1)  # ordered
  File "/home/kuhl/miniconda2/envs/phasebook/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/kuhl/miniconda2/envs/phasebook/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
IndexError: list index out of range

How to fix this? How can I restart from here?

**Comment by HMPNK** [comment]
Same issue happens when running the example file.

**Comment by HMPNK** [comment]
I just found that this issue is due to Installation problems. I was unable to use python3.7 because it was conflicting with my CUDA Version according to bioconda. I installed everything on another System without CUDA and it worked (at least the example)
