### ISSUE TITLE
Docker - Singularity container 

### ISSUE THREAD

**Issue by agesantos** [phasebook/phasebook#36]
Hi, 

After struggling for days to install phasebook using conda I found that [husamia](https://github.com/husamia,  in this other issue -  https://github.com/phasebook/phasebook/issues/2, produced a docker container for phrasebook! 

It even works when installed via singularity!! 
singularity build phasebook.v2.simg docker://husamia/phasebook:v2
 
May you could add it to the installation alternatives? It really saves time for users. 

Thank you for developing this pipeline! 
andré

**Comment by HLHsieh** [comment]
Hi andré,

Thank you!!! I’ve been struggling with using phasebook for quite some time.

However, I am still encountering an error when executing the following command:

```
Singularity> python ../scripts/phasebook.py -i reads.fa -t 8 -p hifi -g small -x
Failed to import the site module
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site.py", line 545, in <module>
    main()
  File "/usr/local/lib/python3.6/site.py", line 531, in main
    known_paths = addusersitepackages(known_paths)
  File "/usr/local/lib/python3.6/site.py", line 282, in addusersitepackages
    user_site = getusersitepackages()
  File "/usr/local/lib/python3.6/site.py", line 258, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/usr/local/lib/python3.6/site.py", line 248, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/usr/local/lib/python3.6/sysconfig.py", line 609, in get_config_var
    return get_config_vars().get(name)
  File "/usr/local/lib/python3.6/sysconfig.py", line 558, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/usr/local/lib/python3.6/sysconfig.py", line 429, in _init_posix
    _temp = __import__(name, globals(), locals(), ['build_time_vars'], 0)
ModuleNotFoundError: No module named '_sysconfigdata_x86_64_conda_cos7_linux_gnu'
```

I was wondering if you’ve encountered a similar issue and, if so, whether you might have any suggestions on how to resolve it.

Thank you.

Best regards,
Hsin

**Comment by agesantos** [comment]
Hi Hsin, 

After installing with singularity as I discribed above, I ran phasebook like this: 

singularity exec phasebook.v2.simg python /phasebook/scripts/phasebook.py -i reads.fa -t 8 -p hifi -g small -x

For the test dataset, it ran smoothly. I am now running for a full dataset but it is still running. 

Sorry, but I don't exactly know why is not working for you. 

All the best,
andré

**Comment by HLHsieh** [comment]
Hi andré,

Thank you! It works and the job has successfully completed.

Many thanks,
Hsin
