### ISSUE TITLE
Errors occured

### ISSUE THREAD

**Issue by iamnotaNL** [phasebook/phasebook#4]
Hi,
When I ran phasebook on the example data, it can run for a while and then terminated with the following messages: 
===================
2021-09-15 15:21:22,630 - ../scripts/phasebook.py[line:261] - INFO: splitting input fastx file into 1 subfiles...
use preset parameters...
2021-09-15 15:21:22,961 - ../scripts/phasebook.py[line:269] - INFO: splitting finished.

2021-09-15 15:21:22,961 - ../scripts/phasebook.py[line:277] - INFO: computing all-vs-all read overlaps...
2021-09-15 15:21:25,157 - ../scripts/phasebook.py[line:284] - INFO: computing overlaps finished.

2021-09-15 15:21:25,157 - ../scripts/phasebook.py[line:289] - INFO: clustering reads...
2021-09-15 15:21:25,223 - ../scripts/phasebook.py[line:298] - INFO: generating read and overlap files for each cluster...
2021-09-15 15:21:25,687 - ../scripts/phasebook.py[line:308] - INFO: stage1 assembly: assemble raw reads for each cluster...
tmp/2.overlap/s1_s1.paf
reading overlap done...
2021-09-15 15:21:30,056 - /mnt/z/phasebook/phasebook/scripts/assembly.py[line:150] - INFO: cluster:6 variant calling started...
2021-09-15 15:21:30,425 - /mnt/z/phasebook/phasebook/scripts/assembly.py[line:150] - INFO: cluster:1 variant calling started...
2021-09-15 15:21:30,540 - /mnt/z/phasebook/phasebook/scripts/assembly.py[line:153] - INFO: cluster:6 reads phasing started...
2021-09-15 15:21:30,954 - /mnt/z/phasebook/phasebook/scripts/assembly.py[line:153] - INFO: cluster:1 reads phasing started...
2021-09-15 15:21:33,468 - /mnt/z/phasebook/phasebook/scripts/assembly.py[line:150] - INFO: cluster:5 variant calling started...
2021-09-15 15:21:33,984 - /mnt/z/phasebook/phasebook/scripts/assembly.py[line:150] - INFO: cluster:3 variant calling started...
2021-09-15 15:21:34,263 - /mnt/z/phasebook/phasebook/scripts/assembly.py[line:153] - INFO: cluster:5 reads phasing started...
2021-09-15 15:21:34,646 - /mnt/z/phasebook/phasebook/scripts/assembly.py[line:153] - INFO: cluster:3 reads phasing started...
2021-09-15 15:21:35,932 - /mnt/z/phasebook/phasebook/scripts/assembly.py[line:150] - INFO: cluster:4 variant calling started...
2021-09-15 15:21:36,623 - /mnt/z/phasebook/phasebook/scripts/assembly.py[line:153] - INFO: cluster:4 reads phasing started...
2021-09-15 15:21:37,110 - /mnt/z/phasebook/phasebook/scripts/assembly.py[line:150] - INFO: cluster:2 variant calling started...
2021-09-15 15:21:37,863 - /mnt/z/phasebook/phasebook/scripts/assembly.py[line:153] - INFO: cluster:2 reads phasing started...
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/mnt/z/phasebook/phasebook/scripts/assembly.py", line 154, in get_superead
    hap2reads = phase_reads(i, vcf, bam, ref, outdir, True,binpath)
  File "/mnt/z/phasebook/phasebook/scripts/phasing.py", line 74, in phase_reads
    read = line.strip().split()[0]
IndexError: list index out of range
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "../scripts/phasebook.py", line 379, in <module>
    sys.exit(main())
  File "../scripts/phasebook.py", line 310, in main
    run_on_local(num_clusters, args.threads, cluster_dir, args.platform, args.min_cov, args.max_tip_len,
  File "/mnt/z/phasebook/phasebook/scripts/parallel.py", line 17, in run_on_local
    pool.map(get_superead, params, chunksize=1)  # ordered
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
IndexError: list index out of range
===================

I found only 3 directories ('1.split_fastx', '2.overlap' and '3.cluster') were produced and in '3.cluster', directories 'c1' to 'c6' were not empty. 
I ran phasebook on 'Ubuntu 20.04.2 LTS'(python=3.8) and 'CentOS Linux release 7.4.1708'(python=3.7), and got the same errors.

Could you please help me resolve these issues. 

Thanks.

**Comment by ZuyaoLiu** [comment]
I got exactly the same issue.
Could you please check it?

Thanks

**Comment by HaploKit** [comment]
Hi, could you go into the folder `3.cluster/c1` and run `whatshap haplotag --reference 1.ref.polished.fa --ignore-read-groups 1.phased.vcf.gz 1.bam| samtools view -|cut -f 1,12- >out.txt` in the phasebook conda environment ? Please check if this command works or not, and if`out.txt` file is empty. If you cannot find these temp files, such as `1.ref.polished.fa, 1.phased.vcf.gz ,...`. please add   `--rm_tmp False` when you run phasebook.

**Comment by iamnotaNL** [comment]
Hi,
When I ran ‘whatshap haplotag --reference 1.ref.polished.fa --ignore-read-groups 1.phased.vcf.gz 1.bam| samtools view -|cut -f 1,12- > out.txt’, the errors are：
Found 1 sample(s) in input VCF
Keeping 1 sample(s) for haplo-tagging
Found 0 sample(s) in BAM file
ERROR: whatshap error: invalid contig `1`

I found there are X.phased.vcf files in c1-c6 dirs, but there are no valid contents in them, ie. they only contain comments lines. So I guess there may be problems in the step for 'phased.vcf' files. 

Thanks.

**Comment by HaploKit** [comment]
Thanks, could you please check these files `1.nophase.vcf` and `1.bam`,are they normal or not ?

**Comment by ZuyaoLiu** [comment]
Hi xiaoluo,

Thanks for developing this tool.
I used to phase assembly with a similar approach but this tool is much more convenient.

So I guess the problem is when running "whatshap phase -o {} --reference {} --ignore-read-groups {} {}" in phasing.py, whatshap does not accept the floating numbers in GQ field in nophase.vcf. This is generated by longshot. I checked the rest directories, and the nophased.vcf contains sites while the phased.vcf contains only the VCF headers.
For example, the 500.00 in GQ field should be 500.

Can you please check it?

Zuyao

**Comment by HaploKit** [comment]
Hi, thank you for your feedback. I guess it is probably due to different versions of dependent tools, so I added the version information when installing them. please see the updated installation guide. It should work now.

**Comment by ZuyaoLiu** [comment]
Hi,

Now the issue is solved. Whatshap should be version 0.18 not the latest 1.1 on Conda.
I leave this here to inform people who might also have this issue.

**Comment by tongyin121** [comment]
Hi,
I got the similar errors after adding the parameter --rm_tmp False when I ran phasebook, and  the contents of the log file are shown in the link file.
[phase.log](https://github.com/phasebook/phasebook/files/7606068/phase.log)
Could you please help me resolve this error.
Thanks
